project:
  type: website
  output-dir: docs

website:
  title: "Research Design"
  site-url: https://briancfox.com/ResearchDesign/
  description: "This is the site for PhD 1506."
  
  
  navbar:
    left:
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: assignment.qmd
        text: Assignments

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source