project:
  type: website
  output-dir: docs

website:
  title: "PhD 1506 - Research Design"
  site-url: https://briancfox.com/ResearchDesign/
  description: "This is the site for PhD 1506."
  
  
  navbar:
    left:
      - href: syllabus.qmd
        text: Syllabus
      - href: classes.qmd
        text: Classes
      - href: https://miro.com/welcomeonboard/M1YrT2hMZUJpQzVXV1FsSExaQWRtaG9FSjZIc0VlVG0ySmcrSHo2WEJDZGx3aWx2MjNXQmtvY3h3cjNaK1lXQ2F3MGlGTitZL2tMMk5TRXpSeVlEKzBTMDI4STYzVjJHVTkwWFlDRkF2YUcxci9ldnYvY1h6bDVOUDNDMUt1d2UhZQ==?share_link_id=81401689235
        text: Miro
      - href: https://app.perusall.com/join/fox-y6vba
        text: Perusall
      - href: https://pollev.com/drfox
        text: PollEverywhere


format:
  html:
    theme: cosmo
    toc: true

editor: source