project:
  type: website
  output-dir: 

website:
  title: "Research Design"
  
  navbar:
    left:
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: assignment.qmd
        text: Assignments

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source