project:
  type: website
  output-dir: docs

website:
  title: "PhD 1506 - Research Design"
  site-url: https://briancfox.com/ResearchDesign/
  description: "This is the site for PhD 1506."
  
  
  navbar:
    left:
      - href: syllabus.qmd
        text: Syllabus
      - href: classes.qmd
        text: Classes
      - href: https://bentleyedu-my.sharepoint.com/:wb:/g/personal/bfox_bentley_edu/EU7pnqwe88pLmzLQkbkVH08Bq2WEgbuLyvHRr3Xhdq0cQA?e=obYdLO
        text: Whiteboard
      - href: https://pollev.com/drfox
        text: PollEverywhere
      - href: https://wrds-www.wharton.upenn.edu/pages/ 
        text: WRDS
      - href: currentevents.qmd
        text: Current Events


format:
  html:
    theme: cosmo
    toc: true

editor: source