project:
  type: website
  output-dir: docs

website:
  title: "PhD 1506 - Research Design"
  site-url: https://briancfox.com/ResearchDesign/
  description: "This is the site for PhD 1506."
  
  
  navbar:
    left:
      - href: syllabus.qmd
        text: Syllabus
      - href: classes.qmd
        text: Classes


format:
  html:
    theme: cosmo
    toc: true

editor: source